// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rvL4Z2jyAqe3umzZYo5sfv
// Component: UGUqJdIfGpP3
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: -zE89ucLXzyA/component
import Button from "../../Button"; // plasmic-import: 98uZdJHb8ovP/component
import ProductCard from "../../ProductCard"; // plasmic-import: CUCpwfWcus3T/component
import Footer from "../../Footer"; // plasmic-import: QMRL2OPgGfRX/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _KXZ2ScVpJRX/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: rvL4Z2jyAqe3umzZYo5sfv/projectcss
import * as sty from "./PlasmicAllSoundKitsPage.module.css"; // plasmic-import: UGUqJdIfGpP3/css
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: PIiokDHdfeaA/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: GtlGcf4PbO_T/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: sD_a7Zz1NElJ/icon

export const PlasmicAllSoundKitsPage__VariantProps = new Array();

export const PlasmicAllSoundKitsPage__ArgProps = new Array();

function PlasmicAllSoundKitsPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Inceptos tempor torquent tortor a aptent parturient a a himenaeos in ipsum ad vestibulum euismod ultrices dis vulputate vestibulum non adipiscing."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen"}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__p8Zcb)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__vHvFy)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__cnwld
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__bd6Hc)}
                    icons={"none"}
                    link2={"/category"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__qw5Sq
                        )}
                      >
                        {"All"}
                      </div>
                    }
                    states={"active"}
                  />

                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__u4Wm1
                      )}
                      icons={"none"}
                      slot={"New"}
                    />
                  ) : null}

                  <Button
                    className={classNames("__wab_instance", sty.button__waj9)}
                    icons={"none"}
                    link2={"/category-2"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___3Ler1
                        )}
                      >
                        {"One Shot Kits"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__vGoAv)}
                    icons={"none"}
                    link2={"/category-3"}
                    slot={"Drum Kits"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___2C1Kn)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__xin4I
                        )}
                      >
                        {"Preset Banks"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__rvAiA)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__bp4Lr
                        )}
                      >
                        {"Loop Kits"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__p6Njp)}
                >
                  {true ? (
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__y2DkW
                      )}
                    >
                      {"Price"}
                    </div>
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__uxUi9
                      )}
                      icons={"none"}
                      slot={"$0 - $50"}
                    />
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames("__wab_instance", sty.button__izO3)}
                      icons={"none"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__kfD2I
                          )}
                        >
                          {"$51 - $99"}
                        </div>
                      }
                    />
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__hyePl
                      )}
                      icons={"none"}
                      slot={"$101+"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__qgibc)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___7IljG
                    )}
                  >
                    {"Producers"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__jN9Y)}
                    icons={"none"}
                    link2={"/Home"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__grDsd
                        )}
                      >
                        {"LOXDED"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__ahStS)}
                    icons={"none"}
                    link2={"/Home"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__cooXf
                        )}
                      >
                        {"BKB"}
                      </div>
                    }
                  />

                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__tyGjS
                      )}
                      icons={"none"}
                      slot={"Crocs"}
                    />
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__wJe57
                      )}
                      icons={"none"}
                      slot={"Fila"}
                    />
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__hWiLf
                      )}
                      icons={"none"}
                      slot={"Nike"}
                    />
                  ) : null}
                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ew6Ka
                      )}
                      icons={"none"}
                      slot={"Puma"}
                    />
                  ) : null}

                  <Button
                    className={classNames("__wab_instance", sty.button__xlTyb)}
                    icons={"none"}
                    slot={
                      true ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__pvm26
                          )}
                        >
                          {"Reebok"}
                        </div>
                      ) : null
                    }
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__xvspb)}
              >
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__pm6TS
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__iDjBi)}
                        role={"img"}
                        src={
                          "/plasmic/ecommerce_starter/images/untitledDrawing10Png.png"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    {true ? (
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__u18Vy
                        )}
                      >
                        {"LOXDED - Drippy One Shot Kit"}
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___3E9Ln
                        )}
                      >
                        {"One Shot Kit"}
                      </div>
                    ) : null}
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___0XvUd
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__lWxXl)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__lINe
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ciE8
                      )}
                    >
                      {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__eoHOj
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__mfL2T)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__nSmr
                      )}
                    >
                      {"Question Low Men's Basketball Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__dHwN8
                      )}
                    >
                      {"Lace up fierce baller style."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__mdQdz
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__cmK3)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ddTk3
                      )}
                    >
                      {"Cali Women's Sneakers"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__xeYWn
                      )}
                    >
                      {"A sport style turned street classic."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___8Zv4A
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__dPcmV)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__mtCz7
                      )}
                    >
                      {"MAGIC SPEED"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__t403U
                      )}
                    >
                      {"mMade for racing or regular training runs."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__atOvs
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__isMbS)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__dtEg
                      )}
                    >
                      {"Pride Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___0PRGy
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__i90Ea
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__s4Lv1)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__eewcD
                      )}
                    >
                      {"Nike Air Zoom Pegasus 38"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ydHf
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___3TMpC
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__hSiy7)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__qNq72
                      )}
                    >
                      {"GEL-Nimbus 22 Retro Tokyo"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ngNWx
                      )}
                    >
                      {"Enjoy comfort with each stride."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___2Fhrh
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__abi0H)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__s5Bwm
                      )}
                    >
                      {"A Bug's World Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__puqSm
                      )}
                    >
                      {"Allover glow-in-the-dark bug prints."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__zpyTw
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__qu32O)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hwZbm
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__bUmvw
                      )}
                    >
                      {
                        "Effortlessly step up your look than a pop of animal print."
                      }
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__o9TMr
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__cRzd4)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__xNtu7
                      )}
                    >
                      {"Suede Teams Little Kids' Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___5XjQz
                      )}
                    >
                      {"Worn by the icons of every generation."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___1RGDn
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__bAibE)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__iYyZ
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___6RAr3
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__un6W
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__vRecC)}
                        role={"img"}
                        src={
                          "https://pyxis.nymag.com/v1/imgs/537/58a/ddd6aab90b2387c93d86216de49dccfe4b-madewell-court-sneaker.2x.rsquare.w600.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__l6XOa
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kpi1
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__mozAy
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__bdsJe)}
                        role={"img"}
                        src={
                          "https://cdn.shopify.com/s/files/1/2495/5044/products/oca-low-green-canvas-sneaker.slideshow1.jpg?v=1610694945"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__r2O1G
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__jiYIn
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__cbrEd
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___4D4W)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/38277b478a79419abf6da998000ab640_9366/Runfalcon_Shoes_Black_F36218_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___4Mlbp
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kl6Ik
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__sJvr8
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__vtiwo)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_600,f_auto,q_auto/4e894c2b76dd4c8e9013aafc016047af_9366/Superstar_Shoes_White_FV3284_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__xLo7I
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___4LPzf
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___4XhEg)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__sEg4C
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__vp3T)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__sg4Ff)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__i6Acu
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__m0SBy
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__nPkpI)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__tqJxM
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__iapJh
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__sjFq)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__eWhNe)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__rYnLb
                    )}
                  >
                    {"More info"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__ndReB)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__gA5Cm)}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ukBc
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__kxSnb
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___4Slpu
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__tlm8U)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___9QMwu
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__pzLl2
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__sP4St
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAllSoundKitsPage__ArgProps,
      internalVariantPropNames: PlasmicAllSoundKitsPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicAllSoundKitsPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAllSoundKitsPage";
  } else {
    func.displayName = `PlasmicAllSoundKitsPage.${nodeName}`;
  }
  return func;
}

export const PlasmicAllSoundKitsPage = Object.assign(
  // Top-level PlasmicAllSoundKitsPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicAllSoundKitsPage
    internalVariantProps: PlasmicAllSoundKitsPage__VariantProps,
    internalArgProps: PlasmicAllSoundKitsPage__ArgProps
  }
);

export default PlasmicAllSoundKitsPage;
/* prettier-ignore-end */
