// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rvL4Z2jyAqe3umzZYo5sfv
// Component: UDoNitmZ9tjB
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: -zE89ucLXzyA/component
import Button from "../../Button"; // plasmic-import: 98uZdJHb8ovP/component
import ProductCard from "../../ProductCard"; // plasmic-import: CUCpwfWcus3T/component
import Footer from "../../Footer"; // plasmic-import: QMRL2OPgGfRX/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _KXZ2ScVpJRX/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: rvL4Z2jyAqe3umzZYo5sfv/projectcss
import * as sty from "./PlasmicOneShotSoundKitsPage.module.css"; // plasmic-import: UDoNitmZ9tjB/css
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: PIiokDHdfeaA/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: GtlGcf4PbO_T/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: sD_a7Zz1NElJ/icon

export const PlasmicOneShotSoundKitsPage__VariantProps = new Array();

export const PlasmicOneShotSoundKitsPage__ArgProps = new Array();

function PlasmicOneShotSoundKitsPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen"}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__dFoKt)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__u7Xd5)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___8RYh0
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__ugu2J)}
                    icons={"none"}
                    link2={"/category"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__hhmh
                        )}
                      >
                        {"All"}
                      </div>
                    }
                  />

                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__kvvg4
                      )}
                      icons={"none"}
                      slot={"New"}
                    />
                  ) : null}

                  <Button
                    className={classNames("__wab_instance", sty.button__cDx4)}
                    icons={"none"}
                    link2={"/category-2"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___1I3J
                        )}
                      >
                        {"One Shot Kits"}
                      </div>
                    }
                    states={"active"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__wmpzf)}
                    icons={"none"}
                    link2={"/category-3"}
                    slot={"Drum Kits"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___7XxJe)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__dUlF6
                        )}
                      >
                        {"Preset Banks"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__ntth6)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___5K06
                        )}
                      >
                        {"Loop Kits"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__o2XdE)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__mbm34
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button___1EVqD)}
                    icons={"none"}
                    slot={"$0 - $50"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__glfOy)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__ib2Jj
                        )}
                      >
                        {"$51 - $99"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__a7TLd)}
                    icons={"none"}
                    slot={"$101+"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__aL4L)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___0KBxk
                    )}
                  >
                    {"Producers"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__iByUw)}
                    icons={"none"}
                    slot={"Adidas"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__g5PKj)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___5QfoJ
                        )}
                      >
                        {"Asics"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__fVv3)}
                    icons={"none"}
                    slot={"Crocs"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__rfz5T)}
                    icons={"none"}
                    slot={"Fila"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__vPos)}
                    icons={"none"}
                    slot={"Nike"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__sSw0U)}
                    icons={"none"}
                    slot={"Puma"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__aPriE)}
                    icons={"none"}
                    slot={"Reebok"}
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__ntl1O)}
              >
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__ndJae
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__aifS7)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__yYkDt
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hPdvL
                      )}
                    >
                      {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__fdFfN
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__jfPwe)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___5SVE
                      )}
                    >
                      {"Question Low Men's Basketball Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__pIzM3
                      )}
                    >
                      {"Lace up fierce baller style."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__uHprj
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__yJyc1)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__fBmwd
                      )}
                    >
                      {"Cali Women's Sneakers"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___3Ka1D
                      )}
                    >
                      {"A sport style turned street classic."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___9T7Bt
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__jm5Be)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__xxqOl
                      )}
                    >
                      {"MAGIC SPEED"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__pPxw3
                      )}
                    >
                      {"mMade for racing or regular training runs."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__kNh4L
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___3BsJj)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__uHpYy
                      )}
                    >
                      {"Pride Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__lYRre
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___3DqGe
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__a5PmP)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__quOc3
                      )}
                    >
                      {"Nike Air Zoom Pegasus 38"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__qKgDv
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__a1EA5
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__kua8Z)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___7GysL
                      )}
                    >
                      {"GEL-Nimbus 22 Retro Tokyo"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__cvGEa
                      )}
                    >
                      {"Enjoy comfort with each stride."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__sGHt6
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__nHu7B)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gf6U
                      )}
                    >
                      {"A Bug's World Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__t0Xx9
                      )}
                    >
                      {"Allover glow-in-the-dark bug prints."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___4H9ZL
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___310B2)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kaz1Z
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__uzziw
                      )}
                    >
                      {
                        "Effortlessly step up your look than a pop of animal print."
                      }
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__liVuH
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___8N5B4)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__pEkRl
                      )}
                    >
                      {"Suede Teams Little Kids' Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hySM
                      )}
                    >
                      {"Worn by the icons of every generation."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gwhQv
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__pgaGo)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__rScPu
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__w7OCh
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__skRb9
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__vs1Sd)}
                        role={"img"}
                        src={
                          "https://pyxis.nymag.com/v1/imgs/537/58a/ddd6aab90b2387c93d86216de49dccfe4b-madewell-court-sneaker.2x.rsquare.w600.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__mh7Zq
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__tiJf
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__lYhv
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ginj)}
                        role={"img"}
                        src={
                          "https://cdn.shopify.com/s/files/1/2495/5044/products/oca-low-green-canvas-sneaker.slideshow1.jpg?v=1610694945"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__bqfJ2
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ka8D7
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__rym3J
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__wxO2)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/38277b478a79419abf6da998000ab640_9366/Runfalcon_Shoes_Black_F36218_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__ddh9
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__qeJ4T
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__eRjjl
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__puoz4)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_600,f_auto,q_auto/4e894c2b76dd4c8e9013aafc016047af_9366/Superstar_Shoes_White_FV3284_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__sMil0
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__k8GdK
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__iauj9)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___6GYlO
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__j0KZh
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__eMEjk)}
                    colors={"black"}
                    icons={"none"}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__kPe3Q)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__nvlXu
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__kPwpA)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg___7GCb0)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xGjso
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__hiVjg
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__taHcf)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__nM1Gv
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__mMihY
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__d9SNl)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__oobj)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__x0RnN
                    )}
                  >
                    {"More info"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__z1Ar)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__vZjrg)}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__tpJd4
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___3AgHg
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ny9Tb
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__lrjF)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__kxe10
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__kSNk4
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__hDvrs
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer", "textbox"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOneShotSoundKitsPage__ArgProps,
      internalVariantPropNames: PlasmicOneShotSoundKitsPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicOneShotSoundKitsPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOneShotSoundKitsPage";
  } else {
    func.displayName = `PlasmicOneShotSoundKitsPage.${nodeName}`;
  }
  return func;
}

export const PlasmicOneShotSoundKitsPage = Object.assign(
  // Top-level PlasmicOneShotSoundKitsPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicOneShotSoundKitsPage
    internalVariantProps: PlasmicOneShotSoundKitsPage__VariantProps,
    internalArgProps: PlasmicOneShotSoundKitsPage__ArgProps
  }
);

export default PlasmicOneShotSoundKitsPage;
/* prettier-ignore-end */
