// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rvL4Z2jyAqe3umzZYo5sfv
// Component: Yn2CNkzAyrNw
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: -zE89ucLXzyA/component
import Button from "../../Button"; // plasmic-import: 98uZdJHb8ovP/component
import ProductCard from "../../ProductCard"; // plasmic-import: CUCpwfWcus3T/component
import Footer from "../../Footer"; // plasmic-import: QMRL2OPgGfRX/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _KXZ2ScVpJRX/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: rvL4Z2jyAqe3umzZYo5sfv/projectcss
import * as sty from "./PlasmicDrumKitSoundKitsPage2.module.css"; // plasmic-import: Yn2CNkzAyrNw/css
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: PIiokDHdfeaA/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: GtlGcf4PbO_T/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: sD_a7Zz1NElJ/icon

export const PlasmicDrumKitSoundKitsPage2__VariantProps = new Array();

export const PlasmicDrumKitSoundKitsPage2__ArgProps = new Array();

function PlasmicDrumKitSoundKitsPage2__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen"}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___4RWqD)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__hbSbW)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__ck4V5
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__o3Kmh)}
                    icons={"none"}
                    link2={"/category"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__erdk
                        )}
                      >
                        {"All"}
                      </div>
                    }
                  />

                  {true ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__jHkzt
                      )}
                      icons={"none"}
                      slot={"New"}
                    />
                  ) : null}

                  <Button
                    className={classNames("__wab_instance", sty.button__nnGv5)}
                    icons={"none"}
                    link2={"/category-2"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__apV7L
                        )}
                      >
                        {"One Shot Kits"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___9Qh0)}
                    icons={"none"}
                    link2={"/category-3"}
                    slot={"Drum Kits"}
                    states={"active"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__rlaTh)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__lxgo
                        )}
                      >
                        {"Preset Banks"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__wQpc)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__mmEv4
                        )}
                      >
                        {"Loop Kits"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___9WThT)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__z3NCj
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__q0AeA)}
                    icons={"none"}
                    slot={"$0 - $50"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__j5Z1L)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__ulyBy
                        )}
                      >
                        {"$51 - $99"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___7SI1P)}
                    icons={"none"}
                    slot={"$101+"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___1J3H)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__qVr4H
                    )}
                  >
                    {"Producers"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__salpS)}
                    icons={"none"}
                    slot={"Adidas"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__h7OGj)}
                    icons={"none"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__vW03T
                        )}
                      >
                        {"Asics"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__jiGr8)}
                    icons={"none"}
                    slot={"Crocs"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__fkoZv)}
                    icons={"none"}
                    slot={"Fila"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__s8NS)}
                    icons={"none"}
                    slot={"Nike"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___7ZWzh)}
                    icons={"none"}
                    slot={"Puma"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__zg4Mc)}
                    icons={"none"}
                    slot={"Reebok"}
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__jg5Vy)}
              >
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__frjlp
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__nE8Cq)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__b5JSa
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__vds9K
                      )}
                    >
                      {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__z8ONg
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ePrC0)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__vVkQ6
                      )}
                    >
                      {"Question Low Men's Basketball Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__eSpn6
                      )}
                    >
                      {"Lace up fierce baller style."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gtrjb
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__xixsq)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__cjkf
                      )}
                    >
                      {"Cali Women's Sneakers"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__owXyL
                      )}
                    >
                      {"A sport style turned street classic."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__qJktL
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___9Bmh0)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___4NjV6
                      )}
                    >
                      {"MAGIC SPEED"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___7ESdE
                      )}
                    >
                      {"mMade for racing or regular training runs."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__rwTj9
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ujO4A)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__l79J1
                      )}
                    >
                      {"Pride Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__dEjJ
                      )}
                    >
                      {"If you can dream it, you can build it."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__wBmMs
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ryCkv)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__tTt2
                      )}
                    >
                      {"Nike Air Zoom Pegasus 38"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hwf5K
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__luSvo
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__zXPty)}
                        role={"img"}
                        src={
                          "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__scfOk
                      )}
                    >
                      {"GEL-Nimbus 22 Retro Tokyo"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__wMhRb
                      )}
                    >
                      {"Enjoy comfort with each stride."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__zt7XV
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__hQv2)}
                        role={"img"}
                        src={
                          "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__m1MZq
                      )}
                    >
                      {"A Bug's World Chuck Taylor All Star"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__m8999
                      )}
                    >
                      {"Allover glow-in-the-dark bug prints."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__aKdv0
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__owrSu)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__oEm6Q
                      )}
                    >
                      {"NMD_R1 SHOES"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__bIWmt
                      )}
                    >
                      {
                        "Effortlessly step up your look than a pop of animal print."
                      }
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__dbbmb
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__jmjR6)}
                        role={"img"}
                        src={
                          "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__dRt6E
                      )}
                    >
                      {"Suede Teams Little Kids' Shoes"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kQrjU
                      )}
                    >
                      {"Worn by the icons of every generation."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__fOcB8
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__ccHcJ)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__vAh2W
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__cpbA
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__kHj4G
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__auF4A)}
                        role={"img"}
                        src={
                          "https://pyxis.nymag.com/v1/imgs/537/58a/ddd6aab90b2387c93d86216de49dccfe4b-madewell-court-sneaker.2x.rsquare.w600.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gKz86
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__m9PsH
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__uImnH
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__hcLkh)}
                        role={"img"}
                        src={
                          "https://cdn.shopify.com/s/files/1/2495/5044/products/oca-low-green-canvas-sneaker.slideshow1.jpg?v=1610694945"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__lnWdu
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hcJuo
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__iRaqx
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___8LGcj)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/38277b478a79419abf6da998000ab640_9366/Runfalcon_Shoes_Black_F36218_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kt9F4
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___7SQv
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
                {true ? (
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__kyQbM
                    )}
                    image={
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__h63Pm)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/w_600,f_auto,q_auto/4e894c2b76dd4c8e9013aafc016047af_9366/Superstar_Shoes_White_FV3284_01_standard.jpg"
                        }
                      />
                    }
                    link={"/item"}
                    small={"small"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__zRtp
                      )}
                    >
                      {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__n6LU
                      )}
                    >
                      {"Your workhorse with wings returns."}
                    </div>
                  </ProductCard>
                ) : null}
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__jUtTh)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__cCMkz
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__jQz1V
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…"}
                    size={1}
                    type={"text"}
                    value={""}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__vRkCm)}
                    colors={"black"}
                    icons={"none"}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__wJDv)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__xLrTg
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__vE4Xp)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__l8Q0R)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__gZhs4
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ueUkn
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__uoe2M)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__murnO
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__qoq7F
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__zs5Bg)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__oCPn9)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___0ZuJu
                    )}
                  >
                    {"More info"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__cDp4M)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__j4W2W)}
                    >
                      <Button icons={"none"} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__sDpT0
                        )}
                        icons={"none"}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__daxU
                        )}
                        icons={"none"}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__g71XE
                        )}
                        icons={"none"}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__ocSbT)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___5XPao
                        )}
                        icons={"none"}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ae4Jy
                        )}
                        icons={"none"}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__oMyIi
                        )}
                        icons={"none"}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer", "textbox"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicDrumKitSoundKitsPage2__ArgProps,
      internalVariantPropNames: PlasmicDrumKitSoundKitsPage2__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicDrumKitSoundKitsPage2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDrumKitSoundKitsPage2";
  } else {
    func.displayName = `PlasmicDrumKitSoundKitsPage2.${nodeName}`;
  }
  return func;
}

export const PlasmicDrumKitSoundKitsPage2 = Object.assign(
  // Top-level PlasmicDrumKitSoundKitsPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicDrumKitSoundKitsPage2
    internalVariantProps: PlasmicDrumKitSoundKitsPage2__VariantProps,
    internalArgProps: PlasmicDrumKitSoundKitsPage2__ArgProps
  }
);

export default PlasmicDrumKitSoundKitsPage2;
/* prettier-ignore-end */
