// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rvL4Z2jyAqe3umzZYo5sfv
// Component: LvNYNoGEgNma
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: -zE89ucLXzyA/component
import Button from "../../Button"; // plasmic-import: 98uZdJHb8ovP/component
import Footer from "../../Footer"; // plasmic-import: QMRL2OPgGfRX/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _KXZ2ScVpJRX/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: rvL4Z2jyAqe3umzZYo5sfv/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: LvNYNoGEgNma/css
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: jhfGv_-XMeYa/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: PIiokDHdfeaA/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: GtlGcf4PbO_T/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: irD0DWuLYo36/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"TheSauceVault"}</title>
        <meta key="og:title" property="og:title" content={"TheSauceVault"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__cDbSq)}>
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
            ) ? (
              <img
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(defaultcss.img, sty.img)}
                role={"img"}
                src={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "/plasmic/ecommerce_starter/images/untitledDrawing3Png2.png"
                    : undefined
                }
              />
            ) : null}
          </section>

          <section className={classNames(defaultcss.all, sty.section__ekdvc)}>
            <Button
              className={classNames("__wab_instance", sty.button__xszLx)}
              colors={"lightGrayOutline"}
              link2={"/category"}
              slot={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__nOs3Q
                  )}
                >
                  {"Shop All Kits"}
                </div>
              }
            >
              <Icon4Icon
                className={classNames(defaultcss.all, sty.svg__cacDe)}
                role={"img"}
              />
            </Button>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__ob6Xf
              )}
            >
              {"One Shot Kits | Drum Kits | Preset Banks | Loop Kits"}
            </div>

            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
            ) ? (
              <Button
                className={classNames("__wab_instance", sty.button__mypkJ)}
                colors={"lightGrayOutline"}
                link2={"/category"}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__wptXh
                    )}
                  >
                    {"Shop All Kits"}
                  </div>
                }
              >
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Icon4Icon
                    className={classNames(defaultcss.all, sty.svg__d2OLg)}
                    role={"img"}
                  />
                ) : null}
              </Button>
            ) : null}
          </section>

          <section className={classNames(defaultcss.all, sty.section___7Xj94)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__vOgyp
              )}
            >
              {"FEATURED ITEMS"}
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__a2A8)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__skCh4
                    )}
                  >
                    {"Producers"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__jlKkW)}
                  >
                    {true ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__nrHWz
                        )}
                        slot={"Order status"}
                      >
                        <Icon22Icon
                          className={classNames(defaultcss.all, sty.svg__h7G9L)}
                          role={"img"}
                        />
                      </Button>
                    ) : null}
                    {true ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__kqRpa
                        )}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__gxeUb
                            )}
                          >
                            {"Returns and exchanges"}
                          </div>
                        }
                      >
                        <Icon21Icon
                          className={classNames(defaultcss.all, sty.svg__nJqGm)}
                          role={"img"}
                        />
                      </Button>
                    ) : null}

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__qnMxO
                      )}
                      link2={
                        "https://www.youtube.com/channel/UCatorRGa-e2OckJJaHMdbtw/videos"
                      }
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__maKut
                          )}
                        >
                          {"LOXDED (Founder & CEO)"}
                        </div>
                      }
                    >
                      <Icon28Icon
                        className={classNames(defaultcss.all, sty.svg__vogp)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___2VDic
                      )}
                      link2={
                        "https://www.youtube.com/channel/UCgjlsfArtc8UFxtw7nKAXCw"
                      }
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__kEB
                          )}
                        >
                          {"Brownkidbeats"}
                        </div>
                      }
                    >
                      <Icon28Icon
                        className={classNames(defaultcss.all, sty.svg__grr3G)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__r5Def)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__f5PaX
                    )}
                  >
                    {"Pages"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__jijLh)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox___5Xqj)}
                    >
                      <Button
                        icons={"none"}
                        link2={"/category-2"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__gWpnG
                            )}
                          >
                            {"One Shot Kits"}
                          </div>
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ecHdg
                        )}
                        icons={"none"}
                        link2={"/category-3"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__qtDd7
                            )}
                          >
                            {"Drum Kits"}
                          </div>
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___8WgYq
                        )}
                        icons={"none"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox___9Cyxm
                            )}
                          >
                            {"Preset Banks"}
                          </div>
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__y7Jgb
                        )}
                        icons={"none"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__rdnR9
                            )}
                          >
                            {"Loop Kits"}
                          </div>
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__s8WAs
                        )}
                        icons={"none"}
                        slot={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__iQeG
                              )}
                            >
                              {"Careers"}
                            </div>
                          ) : null
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___4PsOr
                        )}
                        icons={"none"}
                        slot={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__xo7B6
                              )}
                            >
                              {"Sitemap"}
                            </div>
                          ) : null
                        }
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__yZvE1)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__yeo9E
                        )}
                        icons={"none"}
                        slot={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__gmIq
                              )}
                            >
                              {"Group sales"}
                            </div>
                          ) : null
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__gUlLu
                        )}
                        icons={"none"}
                        slot={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__caDaC
                              )}
                            >
                              {"Privacy policy"}
                            </div>
                          ) : null
                        }
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__o7W9K
                        )}
                        icons={"none"}
                        slot={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__pAsuy
                              )}
                            >
                              {"Contact us"}
                            </div>
                          ) : null
                        }
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navBar", "img", "footer"],
  navBar: ["navBar"],
  img: ["img"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    img: makeNodeComponent("img"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
